[package]
name = "tether"
version = "0.1.0"
authors = ["Ram Kaniyur <quadrupleslap@gmail.com>"]

[dependencies]
cfg-if = "0.1"

#TODO: Remove git stuff.

[target.'cfg(target_os = "linux")'.dependencies]
glib = { git = "https://github.com/gtk-rs/glib" }
gtk = { git = "https://github.com/gtk-rs/gtk", features = ["v3_10"] }
webkit2gtk = { git = "https://github.com/gtk-rs/webkit2gtk-rs", features = ["v2_8"] }
